AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 120

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  Exclude:
    - test/**/*


Lint/EmptyBlock:
  Enabled: false
