# frozen_string_literal: true

module Rito
  # Static reference for League queue ids as they appear in match data
  # (match-v5 `queueId`, the `queue` filter on match lists, ...). Frozen
  # snapshot of the League client's game select data.
  #
  #   Rito::Queues.find(420).name  # => "Ranked Solo/Duo"
  module Queues
    Queue = Data.define(
      :id, :name, :short_name, :description, :detailed_description,
      :category, :mode, :limited_time, :bot_honoring_allowed
    )

    class << self
      include Enumerable

      def all
        QUEUES
      end

      def find(id)
        return nil if id.nil?

        INDEX[id.to_i]
      end

      alias [] find

      def each(&)
        QUEUES.each(&)
      end
    end

    ROWS = [
      [0, 'Custom', 'Custom', 'Custom', '', :pvp, :other, false, false],
      [1, 'Normal', 'Normal', 'Blind Pick', 'Normal (Blind Pick)', :pvp, :other, false, false],
      [2, 'Normal', 'Normal', 'Blind Pick', 'Normal (Blind Pick)', :pvp, :other, false, false],
      [7, '', '', '', '', :pvp, :other, false, false],
      [8, 'Normal', 'Normal', 'Blind Pick', 'Normal (Blind Pick)', :pvp, :other, false, false],
      [9, 'Ranked Flex', 'Ranked Flex', 'Ranked Flex', '', :pvp, :other, false, false],
      [14, 'Normal', 'Normal', 'Draft Pick', 'Normal (Draft Pick)', :pvp, :other, false, false],
      [16, '', '', '', '', :pvp, :other, false, false],
      [25, '', '', '', '', :pvp, :other, false, false],
      [31, 'Intro', 'Intro', 'Intro', '', :pvp, :other, false, false],
      [32, 'Beginner', 'Beginner', 'Beginner', '', :pvp, :other, false, false],
      [33, 'Intermediate', 'Intermediate', 'Intermediate', '', :pvp, :other, false, false],
      [34, 'Intro', 'Intro', 'Intro', '', :pvp, :other, false, false],
      [35, 'Beginner', 'Beginner', 'Beginner', '', :pvp, :other, false, false],
      [36, 'Intermediate', 'Intermediate', 'Intermediate', '', :pvp, :other, false, false],
      [41, 'Team', 'Team', 'Team', '', :pvp, :other, false, false],
      [42, 'Team', 'Team', 'Team', '', :pvp, :other, false, false],
      [52, 'Beginner', 'Beginner', 'Beginner', '', :pvp, :other, false, false],
      [61, '', '', '', '', :pvp, :other, false, false],
      [62, 'ARAM', 'ARAM', 'ARAM', '', :pvp, :other, false, false],
      [63, 'ARAM', 'ARAM', 'ARAM', '', :pvp, :other, false, false],
      [64, 'ARAM', 'ARAM', 'ARAM', '', :pvp, :other, false, false],
      [65, 'ARAM', 'ARAM', 'ARAM', '', :pvp, :other, false, false],
      [72, '', '', '', '', :pvp, :other, false, false],
      [73, '', '', '', '', :pvp, :other, false, false],
      [75, '', '', '', '', :pvp, :other, false, false],
      [83, '', '', '', '', :pvp, :other, false, false],
      [90, 'The Teemoing', 'The Teemoing', 'The Teemoing', '', :pvp, :other, false, false],
      [91, 'The Teemoing', 'The Teemoing', 'The Teemoing', '', :pvp, :other, false, false],
      [92, 'Level 100 Gauntlet', 'Level 100 Gauntlet', 'Level 100 Gauntlet', '', :pvp, :other, false, false],
      [96, 'Ascension', 'Ascension', 'Ascension', '', :pvp, :other, false, false],
      [97, 'Ascension', 'Ascension', 'Ascension', '', :pvp, :other, false, false],
      [100, 'Normal', 'Normal', 'Blind Pick', 'Normal (Blind Pick)', :pvp, :other, false, false],
      [300, 'Legend of the Poro King', 'Poro King', 'Poro King', '', :pvp, :other, false, false],
      [301, 'Legend of the Poro King', 'Poro King', 'Poro King', '', :pvp, :other, false, false],
      [310, '', '', '', '', :pvp, :other, false, false],
      [314, 'Nexus Siege', 'Nexus Siege', 'Nexus Siege', '', :pvp, :other, false, false],
      [315, 'Nexus Siege', 'Nexus Siege', 'Nexus Siege', '', :pvp, :other, false, false],
      [316, 'Definitely Not Dominion', 'Definitely Not Dominion', 'Definitely Not Dominion', '', :pvp, :other, false, false],
      [317, 'Definitely Not Dominion', 'Definitely Not Dominion', 'Definitely Not Dominion', '', :pvp, :other, false, false],
      [318, 'AR Ultra Rapid Fire', 'ARURF', 'AR Ultra Rapid Fire', '', :pvp, :other, false, false],
      [319, 'AR Ultra Rapid Fire', 'ARURF', 'AR Ultra Rapid Fire', '', :pvp, :other, false, false],
      [320, 'Blood Moon', 'Blood Moon', 'Blood Moon', '', :pvp, :other, false, false],
      [321, 'Blood Moon', 'Blood Moon', 'Blood Moon', '', :pvp, :other, false, false],
      [324, 'ARSR', 'ARSR', 'ARSR', '', :pvp, :other, false, false],
      [325, 'ARSR', 'ARSR', 'ARSR', '', :pvp, :other, false, false],
      [400, 'Normal', 'Normal', 'Draft Pick', 'Normal (Draft Pick)', :pvp, :summoners_rift, false, false],
      [401, 'Normal', 'Normal', 'Draft Pick', 'Normal (Draft Pick)', :pvp, :summoners_rift, false, false],
      [402, 'Normal', 'Normal', 'Draft Pick', 'Normal (Draft Pick)', :pvp, :summoners_rift, false, false],
      [403, 'Normal', 'Normal', 'Draft Pick', 'Normal (Draft Pick)', :pvp, :summoners_rift, false, false],
      [410, 'Ranked', 'Ranked', 'Ranked Draft', '', :pvp, :other, false, false],
      [411, 'Ranked', 'Ranked', 'Ranked Draft', '', :pvp, :other, false, false],
      [412, 'Ranked', 'Ranked', 'Ranked Draft', '', :pvp, :other, false, false],
      [413, 'Ranked', 'Ranked', 'Ranked Draft', '', :pvp, :other, false, false],
      [420, 'Ranked Solo/Duo', 'Ranked Solo/Duo', 'Ranked Solo/Duo', '', :pvp, :summoners_rift, false, false],
      [421, 'Ranked Solo/Duo', 'Ranked Solo/Duo', 'Ranked Solo/Duo', '', :pvp, :summoners_rift, false, false],
      [422, 'Ranked Solo/Duo', 'Ranked Solo/Duo', 'Ranked Solo/Duo', '', :pvp, :summoners_rift, false, false],
      [430, 'Normal', 'Normal', 'Blind Pick', 'Normal (Blind Pick)', :pvp, :summoners_rift, false, false],
      [431, 'Normal', 'Normal', 'Blind Pick', '', :pvp, :summoners_rift, false, false],
      [432, 'Normal', 'Normal', 'Blind Pick', '', :pvp, :summoners_rift, false, false],
      [433, 'Normal', 'Normal', 'Blind Pick', 'Normal (Blind Pick)', :pvp, :summoners_rift, false, false],
      [440, 'Ranked Flex', 'Ranked Flex', 'Ranked Flex', '', :pvp, :summoners_rift, false, false],
      [441, 'Ranked Flex', 'Ranked Flex', 'Ranked Flex', '', :pvp, :summoners_rift, false, false],
      [442, 'Ranked Flex', 'Ranked Flex', 'Ranked Flex', '', :pvp, :summoners_rift, false, false],
      [450, 'ARAM', 'ARAM', 'ARAM', '', :pvp, :aram, false, false],
      [451, '3v3', '3v3', '3v3', '', :pvp, :aram, false, false],
      [452, '1v1', '1v1', '1v1', '', :pvp, :aram, false, false],
      [460, 'Normal', 'Normal', 'Blind Pick', 'Normal (Blind Pick)', :pvp, :other, false, false],
      [461, 'Twisted Treeline 1v1', 'Twisted Treeline 1v1', 'Twisted Treeline 1v1', 'Twisted Treeline 1v1', :pvp, :other, false, false],
      [470, 'Ranked Flex', 'Ranked Flex', 'Ranked Flex', '', :pvp, :other, false, false],
      [480, 'Swiftplay', 'Swiftplay', 'Swiftplay', 'Normal (Swiftplay)', :pvp, :summoners_rift, false, false],
      [481, '', '', '', '', :pvp, :other, false, false],
      [482, '', '', '', '', :pvp, :other, false, false],
      [483, '', '', '', '', :pvp, :other, false, false],
      [490, 'Quickplay', 'Quickplay', 'Quickplay', 'Normal (Quickplay)', :pvp, :summoners_rift, false, false],
      [491, '', '', '', '', :pvp, :other, false, false],
      [492, '', '', '', '', :pvp, :other, false, false],
      [493, '', '', '', '', :pvp, :other, false, false],
      [501, '', '', '', '', :pvp, :other, false, false],
      [502, '', '', '', '', :pvp, :other, false, false],
      [600, 'Blood Moon', 'Blood Moon', 'Blood Moon', '', :pvp, :other, false, false],
      [601, 'Blood Moon', 'Blood Moon', 'Blood Moon', '', :pvp, :other, false, false],
      [610, 'Dark Star: Singularity', 'Dark Star', 'Dark Star: Singularity', '', :pvp, :other, false, false],
      [611, 'Dark Star: Singularity', 'Dark Star', 'Dark Star: Singularity', '', :pvp, :other, false, false],
      [700, 'Clash', 'Clash', 'Clash', '', :pvp, :summoners_rift, false, false],
      [701, 'Clash', 'Clash', 'Clash', '', :pvp, :summoners_rift, false, false],
      [702, '', '', '', '', :pvp, :other, false, false],
      [710, 'Ranked 5s', 'Ranked 5s', 'Ranked 5s', '', :pvp, :summoners_rift, false, false],
      [720, 'Clash', 'Clash', 'Clash', '', :pvp, :aram, false, false],
      [721, 'Clash', 'Clash', 'Clash', '', :pvp, :aram, false, false],
      [740, 'AR Ultra Rapid Fire Clash', 'ARURF Clash', 'AR Ultra Rapid Fire Clash', '', :pvp, :other, false, false],
      [741, 'AR Ultra Rapid Fire Clash', 'ARURF Clash', 'AR Ultra Rapid Fire Clash', '', :pvp, :other, false, false],
      [800, 'Intermediate', 'Intermediate', 'Intermediate', '', :bots, :summoners_rift, false, false],
      [801, 'Co-op vs. AI', 'Co-op vs. AI', 'Co-op vs. AI', '', :bots, :summoners_rift, false, false],
      [810, 'Intro', 'Intro', 'Intro', '', :bots, :summoners_rift, false, false],
      [820, 'Beginner', 'Beginner', 'Beginner', '', :bots, :summoners_rift, false, false],
      [830, 'Intro', 'Intro', 'Intro', '', :bots, :summoners_rift, false, false],
      [831, 'Bots Intro 3v3', 'Bots Intro 3v3', 'Bots Intro 3v3', 'Bots Intro 3v3', :bots, :summoners_rift, false, false],
      [832, 'Bots Intro 1v1', 'Bots Intro 1v1', 'Bots Intro 1v1', 'Bots Intro 1v1', :bots, :summoners_rift, false, false],
      [840, 'Beginner', 'Beginner', 'Beginner', '', :bots, :summoners_rift, false, false],
      [841, 'Bots Easy 3v3', 'Bots Easy 3v3', 'Bots Easy 3v3', 'Bots Easy 3v3', :bots, :summoners_rift, false, false],
      [842, 'Bots Easy 1v1', 'Bots Easy 1v1', 'Bots Easy 1v1', 'Bots Easy 1v1', :bots, :summoners_rift, false, false],
      [850, 'Intermediate', 'Intermediate', 'Intermediate', '', :bots, :summoners_rift, false, false],
      [851, 'Bots Medium 3v3', 'Bots Medium 3v3', 'Bots Medium 3v3', 'Bots Medium 3v3', :bots, :summoners_rift, false, false],
      [852, 'Bots Medium 1v1', 'Bots Medium 1v1', 'Bots Medium 1v1', 'Bots Medium 1v1', :bots, :summoners_rift, false, false],
      [860, 'ARAM 5v5 Bots', 'ARAM 5v5 Bots', 'ARAM 5v5 Bots', 'ARAM 5v5 Bots', :bots, :aram, false, false],
      [861, 'ARAM 1v1 Bots', 'ARAM 1v1 Bots', 'ARAM 1v1 Bots', 'ARAM 1v1 Bots', :pvp, :aram, false, false],
      [862, '', '', '', '', :pvp, :other, false, false],
      [865, '', '', '', '', :pvp, :other, false, false],
      [870, 'Intro', 'Intro', 'Intro', 'Intro', :bots, :summoners_rift, false, false],
      [880, 'Beginner', 'Beginner', 'Beginner', 'Beginner', :bots, :summoners_rift, false, false],
      [890, 'Intermediate', 'Intermediate', 'Intermediate', 'Intermediate', :bots, :summoners_rift, false, false],
      [891, '', '', '', '', :pvp, :other, false, false],
      [893, 'Bots Easy 1v1', 'Bots Easy 1v1', 'Bots Easy 1v1', 'Bots Easy 1v1', :bots, :summoners_rift, false, false],
      [894, '', '', '', '', :pvp, :other, false, false],
      [900, 'AR Ultra Rapid Fire', 'ARURF', 'AR Ultra Rapid Fire', '', :pvp, :other, false, false],
      [901, 'Test : ARURF 1v1', 'Test : ARURF 1v1', 'Test : ARURF 1v1', '', :pvp, :other, false, false],
      [902, 'Test: ARURF 2v2', 'Test: ARURF 2v2', 'Test: ARURF 2v2', '', :pvp, :other, false, false],
      [903, 'Test: ARURF 3v3', 'Test: ARURF 3v3', 'Test: ARURF 3v3', '', :pvp, :other, false, false],
      [904, 'Test: ARURF 4v4', 'Test: ARURF 4v4', 'Test: ARURF 4v4', '', :pvp, :other, false, false],
      [905, 'Test: ARURF 5v5 - SYD', 'Test: ARURF 5v5 - SYD', 'Test: ARURF 5v5 - SYD', '', :pvp, :other, false, false],
      [906, 'Test: ARURF 1v1 - SYD', 'Test: ARURF 1v1 - SYD', 'Test: ARURF 1v1 - SYD', '', :pvp, :other, false, false],
      [907, 'Test: ARURF 2v2 - SYD', 'Test: ARURF 2v2 - SYD', 'Test: ARURF 2v2 - SYD', '', :pvp, :other, false, false],
      [908, 'Test: ARURF 3v3 - SYD', 'Test: ARURF 3v3 - SYD', 'Test: ARURF 3v3 - SYD', '', :pvp, :other, false, false],
      [909, 'Test: ARURF 4v4 - SYD', 'Test: ARURF 4v4 - SYD', 'Test: ARURF 4v4 - SYD', '', :pvp, :other, false, false],
      [910, 'Ascension', 'Ascension', 'Ascension', '', :pvp, :other, false, false],
      [911, 'Test: ARURF 1v0 - SYD', 'Test: ARURF 1v0 - SYD', 'Test: ARURF 1v0 - SYD', '', :pvp, :other, false, false],
      [920, 'Legend of the Poro King', 'Poro King', 'Poro King', '', :pvp, :other, false, false],
      [921, 'Legend of the Poro King', 'Poro King', 'Poro King', '', :pvp, :other, false, false],
      [930, 'ARAM', 'ARAM', 'ARAM', '', :pvp, :aram, false, false],
      [931, 'ARAM', 'ARAM', 'ARAM', '', :pvp, :aram, false, false],
      [940, 'Nexus Siege', 'Nexus Siege', 'Nexus Siege', '', :pvp, :other, false, false],
      [941, 'Nexus Siege', 'Nexus Siege', 'Nexus Siege', '', :pvp, :other, false, false],
      [950, 'Level 100 Gauntlet', 'Level 100 Gauntlet', 'Level 100 Gauntlet', '', :pvp, :other, false, false],
      [951, 'Level 100 Gauntlet', 'Level 100 Gauntlet', 'Level 100 Gauntlet', '', :pvp, :other, false, false],
      [960, 'The Teemoing', 'The Teemoing', 'The Teemoing', '', :pvp, :other, false, false],
      [961, 'The Teemoing', 'The Teemoing', 'The Teemoing', '', :pvp, :other, false, false],
      [970, 'Hexakill', 'Hexakill', 'Hexakill', '', :pvp, :other, false, false],
      [971, 'Hexakill 1v1', 'Hexakill 1v1', 'Hexakill 1v1', 'Hexakill 1v1', :pvp, :other, false, false],
      [980, 'Invasion (Normal)', 'Invasion (Normal)', 'Normal', 'Invasion (Normal)', :pvp, :other, false, false],
      [981, 'Invasion (Normal)', 'Invasion (Normal)', 'Normal', 'Invasion (Normal)', :pvp, :other, false, false],
      [982, 'Invasion (Normal)', 'Invasion (Normal)', 'Normal', 'Invasion (Normal)', :pvp, :other, false, false],
      [990, 'Invasion (Onslaught)', 'Invasion (Onslaught)', 'Onslaught', 'Invasion (Onslaught)', :pvp, :other, false, false],
      [1000, 'Overcharge', 'Overcharge', 'Overcharge', '', :pvp, :other, false, false],
      [1001, 'Overcharge', 'Overcharge', 'Overcharge', '', :pvp, :other, false, false],
      [1010, 'Snow Battle ARURF', 'Snow ARURF', 'Snow Battle ARURF', '', :pvp, :other, false, false],
      [1011, 'Snow Battle ARURF', 'Snow ARURF', 'Snow Battle ARURF', '', :pvp, :other, false, false],
      [1012, 'Snow Battle ARURF', 'Snow ARURF', 'Snow Battle ARURF', '', :pvp, :other, false, false],
      [1020, 'One For All', 'One For All', 'One For All', '', :pvp, :other, false, false],
      [1021, '1v1', '1v1', '1v1', '', :pvp, :other, false, false],
      [1022, '3v3', '3v3', '3v3', '', :pvp, :other, false, false],
      [1023, '2v2', '2v2', '2v2', '', :pvp, :other, false, false],
      [1024, '4v4', '4v4', '4v4', '', :pvp, :other, false, false],
      [1030, 'Odyssey (Intro)', 'Odyssey (Intro)', 'Intro', 'Odyssey (Intro)', :pvp, :other, false, false],
      [1031, 'Odyssey Intro 1v0', 'Odyssey Intro 1v0', 'Odyssey Intro 1v0', 'Odyssey Intro 1v0', :pvp, :other, false, false],
      [1032, 'Odyssey Intro 3v0', 'Odyssey Intro 3v0', 'Odyssey Intro 3v0', 'Odyssey Intro 3v0', :pvp, :other, false, false],
      [1040, 'Odyssey (Cadet)', 'Odyssey (Cadet)', 'Cadet', 'Odyssey (Cadet)', :pvp, :other, false, false],
      [1041, 'Odyssey Easy 1v0', 'Odyssey Easy 1v0', 'Odyssey Easy 1v0', 'Odyssey Easy 1v0', :pvp, :other, false, false],
      [1050, 'Odyssey (Crewmember)', 'Odyssey (Crewmember)', 'Crewmember', 'Odyssey (Crewmember)', :pvp, :other, false, false],
      [1051, 'Odyssey Medium 1v0', 'Odyssey Medium 1v0', 'Odyssey Medium 1v0', 'Odyssey Medium 1v0', :pvp, :other, false, false],
      [1060, 'Odyssey (Captain)', 'Odyssey (Captain)', 'Captain', 'Odyssey (Captain)', :pvp, :other, false, false],
      [1061, 'Odyssey Hard 1v0', 'Odyssey Hard 1v0', 'Odyssey Hard 1v0', 'Odyssey Hard 1v0', :pvp, :other, false, false],
      [1070, 'Odyssey (Onslaught)', 'Odyssey (Onslaught)', 'Onslaught', 'Odyssey (Onslaught)', :pvp, :other, false, false],
      [1071, 'Odyssey Uber 1v0', 'Odyssey Uber 1v0', 'Odyssey Uber 1v0', 'Odyssey Uber 1v0', :pvp, :other, false, false],
      [1090, 'Teamfight Tactics (Normal)', 'Teamfight Tactics (Normal)', 'Normal', 'Teamfight Tactics (Normal)', :pvp, :tft, false, false],
      [1091, '1v0', '1v0', '1v0', '', :pvp, :tft, false, false],
      [1092, '2v0', '2v0', '2v0', '', :pvp, :tft, false, false],
      [1093, '3v0', '3v0', '3v0', '', :pvp, :tft, false, false],
      [1094, '4v0', '4v0', '4v0', '', :pvp, :tft, false, false],
      [1095, '1v7 Bots', '1v7 Bots', '1v7 Bots', '', :pvp, :tft, false, false],
      [1100, 'Teamfight Tactics (Ranked)', 'Teamfight Tactics (Ranked)', 'Ranked', 'Teamfight Tactics (Ranked)', :pvp, :tft, false, false],
      [1101, '1v0 (Ranked)', '1v0 (Ranked)', '1v0 (Ranked)', '', :pvp, :tft, false, false],
      [1102, '2v0 (Ranked)', '2v0 (Ranked)', '2v0 (Ranked)', '', :pvp, :tft, false, false],
      [1110, 'Teamfight Tactics (Tutorial)', 'Teamfight Tactics (Tutorial)', 'Tutorial', '', :pvp, :tft, false, false],
      [1111, 'TFT Simulation', 'TFT Simulation', 'Simulation', '', :pvp, :tft, false, false],
      [1112, 'TFT Simulation (Automated Testing)', 'TFT Simulation (Automated Testing)', 'Simulation (Auto Testing)', '', :pvp, :tft, false, false],
      [1120, 'Teamfight Tactics (Normal Hyper Roll)', 'Teamfight Tactics (Normal Hyper Roll)', 'Normal Hyper Roll', 'Teamfight Tactics (Normal Hyper Roll)', :pvp, :tft, false, false],
      [1121, '1v0 (Normal Hyper Roll)', '1v0 (Normal Hyper Roll)', '1v0 (Normal Hyper Roll)', '', :pvp, :tft, false, false],
      [1122, '2v0 (Normal Hyper Roll)', '2v0 (Normal Hyper Roll)', '2v0 (Normal Hyper Roll)', '', :pvp, :tft, false, false],
      [1130, 'Teamfight Tactics (Hyper Roll)', 'Teamfight Tactics (Hyper Roll)', 'Hyper Roll', 'Teamfight Tactics (Hyper Roll)', :pvp, :tft, false, false],
      [1131, '1v0 (Hyper Roll)', '1v0 (Hyper Roll)', '1v0 (Hyper Roll)', '', :pvp, :tft, false, false],
      [1132, '2v0 (Hyper Roll)', '2v0 (Hyper Roll)', '2v0 (Hyper Roll)', '', :pvp, :tft, false, false],
      [1133, '3v0 (Hyper Roll)', '3v0 (Hyper Roll)', '3v0 (Hyper Roll)', '', :pvp, :tft, false, false],
      [1135, '1v7 (Hyper Roll)', '1v7 (Hyper Roll)', '1v7 (Hyper Roll)', '', :pvp, :tft, false, false],
      [1140, 'Teamfight Tactics (Normal Double Up)', 'Teamfight Tactics (Normal Double Up)', 'Normal Double Up', 'Teamfight Tactics (Normal Double Up)', :pvp, :tft, false, false],
      [1141, 'Teamfight Tactics (Double Up 1v7 Bots)', 'Teamfight Tactics (Double Up 1v7 Bots)', '1v7 Bots (Double Up)', 'Teamfight Tactics (Double Up 1v7 Bots)', :pvp, :tft, false, false],
      [1142, '2v0 (Normal Double Up)', '2v0 (Normal Double Up)', '2v0 (Normal Double Up)', '2v0 (Normal Double Up)', :pvp, :tft, false, false],
      [1143, '4v0 (Normal Double Up)', '4v0 (Normal Double Up)', '4v0 (Normal Double Up)', '4v0 (Normal Double Up)', :pvp, :tft, false, false],
      [1150, 'Teamfight Tactics (Double Up)', 'Teamfight Tactics (Double Up)', 'Double Up', 'Teamfight Tactics (Double Up)', :pvp, :tft, false, false],
      [1151, '2v0 (Double Up)', '2v0 (Double Up)', '2v0 (Double Up)', '2v0 (Double Up)', :pvp, :tft, false, false],
      [1152, '4v0 (Double Up)', '4v0 (Double Up)', '4v0 (Double Up)', '4v0 (Double Up)', :pvp, :tft, false, false],
      [1160, 'Teamfight Tactics (Double Up)', 'Teamfight Tactics (Double Up)', 'Double Up', 'Teamfight Tactics (Double Up)', :pvp, :tft, false, false],
      [1161, '2v0 (Double Up)', '2v0 (Double Up)', '2v0 (Double Up)', '2v0 (Double Up)', :pvp, :tft, false, false],
      [1162, '4v0 (Double Up)', '4v0 (Double Up)', '4v0 (Double Up)', '4v0 (Double Up)', :pvp, :tft, false, false],
      [1170, 'Teamfight Tactics (Fortune\'s Favor)', 'Teamfight Tactics (Fortune\'s Favor)', 'Fortune\'s Favor', 'Teamfight Tactics (Fortune\'s Favor)', :pvp, :tft, false, false],
      [1171, '1v0 (Fortune\'s Favor)', '1v0 (Fortune\'s Favor)', '1v0 (Fortune\'s Favor)', '1v0 (Fortune\'s Favor)', :pvp, :tft, false, false],
      [1172, '2v0 (Fortune\'s Favor)', '2v0 (Fortune\'s Favor)', '2v0 (Fortune\'s Favor)', '2v0 (Fortune\'s Favor)', :pvp, :tft, false, false],
      [1175, '1v7 Bots (Fortune\'s Favor)', '1v7 Bots (Fortune\'s Favor)', '1v7 Bots (Fortune\'s Favor)', '1v7 Bots (Fortune\'s Favor)', :pvp, :tft, false, false],
      [1180, 'Teamfight Tactics (Soul Brawl)', 'Teamfight Tactics (Soul Brawl)', 'Soul Brawl', 'Teamfight Tactics (Soul Brawl)', :pvp, :tft, false, false],
      [1181, '1v0 (Soul Brawl)', '1v0 (Soul Brawl)', '1v0 (Soul Brawl)', '1v0 (Soul Brawl)', :pvp, :tft, false, false],
      [1182, '2v0 (Soul Brawl)', '2v0 (Soul Brawl)', '2v0 (Soul Brawl)', '2v0 (Soul Brawl)', :pvp, :tft, false, false],
      [1185, '1v7 Bots (Soul Brawl)', '1v7 Bots (Soul Brawl)', '1v7 Bots (Soul Brawl)', '1v7 Bots (Soul Brawl)', :pvp, :tft, false, false],
      [1190, 'Teamfight Tactics (Choncc\'s Classic Treasure)', 'Teamfight Tactics (Choncc\'s Classic Treasure)', 'Choncc\'s Classic Treasure', 'Teamfight Tactics (Choncc\'s Classic Treasure)', :pvp, :tft, false, false],
      [1191, '1v0 (Choncc\'s Classic Treasure)', '1v0 (Choncc\'s Classic Treasure)', '1v0 (Choncc\'s Classic Treasure)', '1v0 (Choncc\'s Classic Treasure)', :pvp, :tft, false, false],
      [1192, '2v0 (Choncc\'s Classic Treasure)', '2v0 (Choncc\'s Classic Treasure)', '2v0 (Choncc\'s Classic Treasure)', '2v0 (Choncc\'s Classic Treasure)', :pvp, :tft, false, false],
      [1195, '1v7 Bots (Choncc\'s Treasure)', '1v7 Bots (Choncc\'s Treasure)', '1v7 Bots (Choncc\'s Treasure)', '1v7 Bots (Choncc\'s Treasure)', :pvp, :tft, false, false],
      [1200, 'Nexus Blitz', 'Nexus Blitz', 'Blind Pick', '', :pvp, :other, false, false],
      [1201, '1v1', '1v1', '1v1', '1v1', :pvp, :other, false, false],
      [1210, 'Teamfight Tactics (Choncc\'s Classic Treasure)', 'Teamfight Tactics (Choncc\'s Classic Treasure)', 'Choncc\'s Classic Treasure', 'Teamfight Tactics (Choncc\'s Classic Treasure)', :pvp, :tft, false, false],
      [1211, '1v0 (Choncc\'s Classic Treasure)', '1v0 (Choncc\'s Classic Treasure)', '1v0 (Choncc\'s Classic Treasure)', '1v0 (Choncc\'s Classic Treasure)', :pvp, :tft, false, false],
      [1212, '2v0 (Choncc\'s Classic Treasure)', '2v0 (Choncc\'s Classic Treasure)', '2v0 (Choncc\'s Classic Treasure)', '2v0 (Choncc\'s Classic Treasure)', :pvp, :tft, false, false],
      [1220, 'Tocker\'s Trials', 'Tocker\'s Trials', 'Tocker\'s Trials', 'Tocker\'s Trials', :pvp, :tft, false, false],
      [1271, '', '', '', '', :pvp, :other, false, false],
      [1272, '', '', '', '', :pvp, :other, false, false],
      [1275, '', '', '', '', :pvp, :other, false, false],
      [1300, 'Nexus Blitz', 'Nexus Blitz', 'Blind Pick', '', :pvp, :other, false, false],
      [1301, '1v1', '1v1', '1v1', '1v1', :pvp, :other, false, false],
      [1400, 'Ultimate Spellbook', 'Ultimate Spellbook', 'Ultimate Spellbook', '', :pvp, :other, false, false],
      [1401, 'UltBook 1v1', 'UltBook 1v1', 'UltBook 1v1', 'UltBook 1v1', :pvp, :other, false, false],
      [1402, 'UltBook 2v2', 'UltBook 2v2', 'UltBook 2v2', 'UltBook 2v2', :pvp, :other, false, false],
      [1403, 'UltBook 3v3', 'UltBook 3v3', 'UltBook 3v3', 'UltBook 3v3', :pvp, :other, false, false],
      [1404, 'UltBook 4v4', 'UltBook 4v4', 'UltBook 4v4', 'UltBook 4v4', :pvp, :other, false, false],
      [1405, 'UltBook OCE 5v5', 'UltBook OCE 5v5', 'UltBook OCE 5v5', 'UltBook OCE 5v5', :pvp, :other, false, false],
      [1406, 'UltBook OCE 1v1', 'UltBook OCE 1v1', 'UltBook OCE 1v1', 'UltBook OCE 1v1', :pvp, :other, false, false],
      [1408, 'UltBook OCE 3v3', 'UltBook OCE 3v3', 'UltBook OCE 3v3', 'UltBook OCE 3v3', :pvp, :other, false, false],
      [1409, 'UltBook OCE 4v4', 'UltBook OCE 4v4', 'UltBook OCE 4v4', 'UltBook OCE 4v4', :pvp, :other, false, false],
      [1411, 'UltBook 1v0', 'UltBook 1v0', 'UltBook 1v0', 'UltBook 1v0', :pvp, :other, false, false],
      [1412, 'UltBook OCE 1v0', 'UltBook OCE 1v0', 'UltBook OCE 1v0', 'UltBook OCE 1v0', :pvp, :other, false, false],
      [1601, '', '', '', '', :pvp, :other, false, false],
      [1602, '', '', '', '', :pvp, :other, false, false],
      [1603, '', '', '', '', :pvp, :other, false, false],
      [1604, '', '', '', '', :pvp, :other, false, false],
      [1605, '', '', '', '', :pvp, :other, false, false],
      [1606, '', '', '', '', :pvp, :other, false, false],
      [1607, '', '', '', '', :pvp, :other, false, false],
      [1608, '', '', '', '', :pvp, :other, false, false],
      [1609, '', '', '', '', :pvp, :other, false, false],
      [1611, '', '', '', '', :pvp, :other, false, false],
      [1612, '', '', '', '', :pvp, :other, false, false],
      [1613, '', '', '', '', :pvp, :other, false, false],
      [1614, '', '', '', '', :pvp, :other, false, false],
      [1615, '', '', '', '', :pvp, :other, false, false],
      [1616, '', '', '', '', :pvp, :other, false, false],
      [1617, '', '', '', '', :pvp, :other, false, false],
      [1618, '', '', '', '', :pvp, :other, false, false],
      [1700, 'Arena', 'Arena', 'Arena', 'Arena', :pvp, :other, false, false],
      [1701, '1v0 (Arena)', '1v0 (Arena)', '1v0 (Arena)', '1v0 (Arena)', :pvp, :other, false, false],
      [1704, 'Arena (PBE 2v2)', 'Arena (PBE 2v2)', 'Arena (PBE 2v2)', 'Arena (PBE 2v2)', :pvp, :other, false, false],
      [1710, 'Arena', 'Arena', 'Arena', 'Arena', :pvp, :other, false, false],
      [1720, 'Arena internal', 'Arena internal', 'Arena internal', 'Arena internal', :pvp, :other, false, false],
      [1731, '1v0 (Arena)', '1v0 (Arena)', '1v0 (Arena)', '1v0 (Arena)', :pvp, :other, false, false],
      [1732, '1v0 (Arena)', '1v0 (Arena)', '1v0 (Arena)', '1v0 (Arena)', :pvp, :other, false, false],
      [1740, 'Bravery Arena', 'Bravery Arena', 'Bravery Arena', 'Bravery Arena', :pvp, :other, false, false],
      [1750, 'Arena 3x6', 'Arena 3x6', 'Arena 3x6', 'Arena 3x6', :pvp, :other, false, false],
      [1767, '', '', '', '', :pvp, :other, false, false],
      [1810, 'Swarm', 'Swarm', 'Swarm', 'Swarm', :pvp, :other, false, false],
      [1820, 'Swarm', 'Swarm', 'Swarm', 'Swarm', :pvp, :other, false, false],
      [1830, 'Swarm', 'Swarm', 'Swarm', 'Swarm', :pvp, :other, false, false],
      [1840, 'Swarm', 'Swarm', 'Swarm', 'Swarm', :pvp, :other, false, false],
      [1900, 'Ultra Rapid Fire', 'URF', 'Ultra Rapid Fire', '', :pvp, :other, false, false],
      [2000, 'Tutorial Part 1', 'Tutorial Part 1', 'Tutorial Part 1', '', :pvp, :other, false, false],
      [2010, 'Tutorial Part 2', 'Tutorial Part 2', 'Tutorial Part 2', '', :pvp, :other, false, false],
      [2020, 'Tutorial Part 3', 'Tutorial Part 3', 'Tutorial Part 3', '', :pvp, :other, false, false],
      [2021, '', '', '', '', :pvp, :other, false, false],
      [2200, 'Teamfight Tactics (Normal)', 'Teamfight Tactics (Normal)', 'Normal', 'Teamfight Tactics (Normal)', :pvp, :tft, false, false],
      [2220, '', '', '', '', :pvp, :other, false, false],
      [2300, 'Brawl', 'Brawl', 'Brawl', 'Brawl', :pvp, :other, false, false],
      [2301, 'Brawl 1v1', 'Brawl 1v1', 'Brawl 1v1', 'Brawl 1v1', :pvp, :other, false, false],
      [2302, 'Brawl 2v2', 'Brawl 2v2', 'Brawl 2v2', 'Brawl 2v2', :pvp, :other, false, false],
      [2303, 'Brawl 3v3', 'Brawl 3v3', 'Brawl 3v3', 'Brawl 3v3', :pvp, :other, false, false],
      [2304, 'Brawl 4v4', 'Brawl 4v4', 'Brawl 4v4', 'Brawl 4v4', :pvp, :other, false, false],
      [2305, 'Brawl 1v0', 'Brawl 1v0', 'Brawl 1v0', 'Brawl 1v0', :pvp, :other, false, false],
      [2400, 'ARAM: Mayhem', 'ARAM: Mayhem', 'ARAM: Mayhem', '', :pvp, :aram, false, false],
      [2401, 'ARAM: Mayhem', 'ARAM: Mayhem', 'ARAM: Mayhem', '', :pvp, :aram, false, false],
      [2403, 'ARAM: Mayhem', 'ARAM: Mayhem', 'ARAM: Mayhem', '', :pvp, :aram, false, false],
      [2405, 'ARAM: Mayhem', 'ARAM: Mayhem', 'ARAM: Mayhem', '', :pvp, :aram, false, false],
      [2410, 'ARAM: Mayhem Tournament', 'ARAM: Mayhem Tournament', 'ARAM: Mayhem Tournament', '', :pvp, :aram, false, false],
      [2450, 'ARAM: Mayhem Classic-ish', 'ARAM: Mayhem Classic-ish', 'ARAM: Mayhem Classic-ish', '', :pvp, :aram, true, false],
      [3000, 'TFT Standard Custom', 'TFT Standard Custom', 'TFT Standard Custom', 'TFT Standard Custom', :pvp, :other, false, false],
      [3010, 'TFT Hyper Roll Custom', 'TFT Hyper Roll Custom', 'TFT Hyper Roll Custom', 'TFT Hyper Roll Custom', :pvp, :other, false, false],
      [3020, 'TFT Double Up Custom', 'TFT Double Up Custom', 'TFT Double Up Custom', 'TFT Double Up Custom', :pvp, :other, false, false],
      [3100, 'SR Blind Pick Custom', 'SR Blind Pick Custom', 'SR Blind Pick Custom', 'SR Blind Pick Custom', :pvp, :other, false, false],
      [3110, 'SR Draft Pick Custom', 'SR Draft Pick Custom', 'SR Draft Pick Custom', 'SR Draft Pick Custom', :pvp, :other, false, false],
      [3120, 'SR All Random', 'SR All Random', 'SR All Random', 'SR All Random', :pvp, :other, false, false],
      [3130, 'SR Tournament Draft', 'SR Tournament Draft', 'SR Tournament Draft', 'SR Tournament Draft', :pvp, :other, false, false],
      [3140, 'Multiplayer Practice Tool Custom', 'Multiplayer Practice Tool Custom', 'Multiplayer Practice Tool Custom', 'Multiplayer Practice Tool Custom', :pvp, :other, false, false],
      [3150, '', '', '', '', :pvp, :other, false, false],
      [3200, 'Howling Abyss Blind Custom', 'Howling Abyss Blind Custom', 'Howling Abyss Blind Custom', 'Howling Abyss Blind Custom', :pvp, :other, false, false],
      [3210, 'Howling Abyss Draft Custom', 'Howling Abyss Draft Custom', 'Howling Abyss Draft Custom', 'Howling Abyss Draft Custom', :pvp, :other, false, false],
      [3220, 'Howling Abyss All Random', 'Howling Abyss All Random', 'Howling Abyss All Random', 'Howling Abyss All Random', :pvp, :other, false, false],
      [3230, 'Howling Abyss Tournament Draft Custom', 'Howling Abyss Tournament Draft Custom', 'Howling Abyss Tournament Draft Custom', 'Howling Abyss Tournament Draft Custom', :pvp, :other, false, false],
      [3240, 'ARAM: Mayhem', 'ARAM: Mayhem', 'ARAM: Mayhem', '', :custom, :other, false, false],
      [3250, 'Howling Abyss First Blood', 'Howling Abyss First Blood', 'Howling Abyss First Blood', 'Howling Abyss First Blood', :pvp, :other, false, false],
      [3260, 'Classic Rift', 'Classic (Custom Blind Pick)', 'Classic (Custom Blind Pick)', 'Classic', :custom, :jade, false, false],
      [3261, 'Jade Sydney', 'Jade Sydney', 'Jade Sydney', 'Jade Sydney', :custom, :jade, false, false],
      [3262, 'Classic Rift', 'Classic (Custom Draft Pick)', 'Classic (Custom Draft Pick)', 'Jade Sydney', :custom, :jade, false, false],
      [3270, 'ARAM: Mayhem', 'ARAM: Mayhem', 'ARAM: Mayhem', 'ARAM: Mayhem', :custom, :other, false, false],
      [3280, 'ARAM: Mayhem Classic-ish', 'ARAM: Mayhem Classic-ish', 'ARAM: Mayhem Classic-ish', 'ARAM: Mayhem Classic-ish', :custom, :aram, false, false],
      [4011, '', '', '', '', :pvp, :other, false, false],
      [4016, 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', :pvp, :other, false, false],
      [4017, 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', :pvp, :other, false, false],
      [4018, 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', :pvp, :other, false, false],
      [4019, 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', :pvp, :other, false, false],
      [4020, 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', 'WIPMODEWIP', :pvp, :other, false, false],
      [4033, '', '', '', '', :pvp, :other, false, false],
      [4044, '', '', '', '', :pvp, :other, false, false],
      [4100, '', '', '', '', :pvp, :other, false, false],
      [4101, '', '', '', '', :pvp, :other, false, false],
      [4102, '', '', '', '', :pvp, :other, false, false],
      [4103, '', '', '', '', :pvp, :other, false, false],
      [4106, '', '', '', '', :pvp, :other, false, false],
      [4107, '', '', '', '', :pvp, :other, false, false],
      [4121, '', '', '', '', :pvp, :other, false, false],
      [4122, '', '', '', '', :pvp, :other, false, false],
      [4123, '', '', '', '', :pvp, :other, false, false],
      [4124, '', '', '', '', :pvp, :other, false, false],
      [4126, '', '', '', '', :pvp, :other, false, false],
      [4127, '', '', '', '', :pvp, :other, false, false],
      [4200, 'Doom Bots 5v5', 'Doom Bots 5v5', 'Doom Bots 5v5', 'Doom Bots 5v5', :pvp, :other, false, true],
      [4201, 'Doom Bots 1v1', 'Doom Bots 1v1', 'Doom Bots 1v1', 'Doom Bots 1v1', :pvp, :other, false, true],
      [4202, 'Doom Bots 2v2', 'Doom Bots 2v2', 'Doom Bots 2v2', 'Doom Bots 2v2', :pvp, :other, false, true],
      [4203, 'Doom Bots 3v3', 'Doom Bots 3v3', 'Doom Bots 3v3', 'Doom Bots 3v3', :pvp, :other, false, true],
      [4204, 'Doom Bots 4v4', 'Doom Bots 4v4', 'Doom Bots 4v4', 'Doom Bots 4v4', :pvp, :other, false, true],
      [4205, 'Doom Bots 5v5 - NA', 'Doom Bots 5v5 - NA', 'Doom Bots 5v5 - NA', 'Doom Bots 5v5 - NA', :pvp, :other, false, true],
      [4210, 'Doom Bots', 'Doom Bots', 'Doom Bots', 'Doom Bots', :pvp, :other, false, true],
      [4211, '', '', '', '', :pvp, :other, false, false],
      [4212, '', '', '', '', :pvp, :other, false, false],
      [4220, 'Doom Bots - Hard', 'Doom Bots - Hard', 'Doom Bots - Hard', 'Doom Bots - Hard', :pvp, :other, false, true],
      [4221, '', '', '', '', :pvp, :other, false, false],
      [4222, '', '', '', '', :pvp, :other, false, false],
      [4240, 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', :pvp, :other, true, true],
      [4241, 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', :pvp, :other, true, true],
      [4242, 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', 'DOOM BOTS - VEIGAR\'S CURSE!', :pvp, :other, true, true],
      [4250, 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', :pvp, :other, true, true],
      [4251, 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', :pvp, :other, true, true],
      [4252, 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', 'DOOM BOTS - VEIGAR\'S EVIL!', :pvp, :other, true, true],
      [4260, 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', :pvp, :other, true, true],
      [4261, 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', :pvp, :other, true, true],
      [4262, 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', 'DOOM BOTS - VEIGAR\'S DOOM!', :pvp, :other, true, true],
      [4300, '5v5 Jade', 'Classic', '5v5 Classic', '5v5 Jade', :pvp, :jade, false, false],
      [4301, '1v1 Jade', '1v1 Classic', '1v1 Classic', '1v1 Jade', :pvp, :jade, false, false],
      [4302, '2v2 Jade', '2v2 Classic', '2v2 Classic', '2v2 Jade', :pvp, :jade, false, false],
      [4303, '3v3 Jade', '3v3 Classic', '3v3 Classic', '3v3 Jade', :pvp, :jade, false, false],
      [4304, '4v4 Jade', '4v4 Classic', '4v4 Classic', '4v4 Jade', :pvp, :jade, false, false],
      [4305, '5v5 Jade Sydney', '5v5 Classic Sydney', '5v5 Classic Sydney', '5v5 Jade Sydney', :pvp, :jade, false, false],
      [4306, '1v1 Jade Sydney', '1v1 Classic Sydney', '1v1 Classic Sydney', '1v1 Jade Sydney', :pvp, :jade, false, false],
      [4307, '2v2 Jade Sydney', '2v2 Classic Sydney', '2v2 Classic Sydney', '2v2 Jade Sydney', :pvp, :jade, false, false],
      [4308, '3v3 Jade Sydney', '3v3 Classic Sydney', '3v3 Classic Sydney', '3v3 Jade Sydney', :pvp, :jade, false, false],
      [4309, '4v4 Jade Sydney', '4v4 Classic Sydney', '4v4 Classic Sydney', '4v4 Jade Sydney', :pvp, :jade, false, false],
      [4310, '', 'Classic', 'Classic 5v5', '', :pvp, :jade, false, true],
      [4311, '1v1 Jade Ranked', '', '', '', :pvp, :jade, false, false],
      [4320, 'Jade', 'Classic', 'Classic Co-op vs. AI', 'Jade', :bots, :jade, false, false],
      [4321, 'Jade', 'Classic', 'Classic Co-op vs. AI 1v1', 'Jade', :bots, :jade, false, false],
      [6000, 'Teamfight Tactics (Set 3.5 Revival: Galaxies)', 'Teamfight Tactics (Set 3.5 Revival: Galaxies)', 'Set 3.5 Revival: Galaxies', 'Teamfight Tactics (Set 3.5 Revival: Galaxies)', :pvp, :tft, false, false],
      [6001, '1v0 (Set 3.5 Revival: Galaxies)', '1v0 (Set 3.5 Revival: Galaxies)', '1v0 (Set 3.5 Revival: Galaxies)', '1v0 (Set 3.5 Revival: Galaxies)', :pvp, :tft, false, false],
      [6002, '1v0 (Set 4.5 Revival)', '1v0 (Set 4.5 Revival)', '1v0 (Set 4.5 Revival)', '1v0 (Set 4.5 Revival)', :pvp, :tft, false, false],
      [6005, '1v7 Bots (Set 3.5 Revival: Galaxies)', '1v7 Bots (Set 3.5 Revival: Galaxies)', '1v7 Bots (Set 3.5 Revival: Galaxies)', '1v7 Bots (Set 3.5 Revival: Galaxies)', :pvp, :tft, false, false],
      [6010, 'Set Queue 1', 'Set Queue 1', 'Set Queue 1', 'Set Queue 1', :pvp, :tft, false, false],
      [6015, 'Set Queue 1 1v7', 'Set Queue 1 1v7', 'Set Queue 1 1v7', 'Set Queue 1 1v7', :pvp, :tft, false, false],
      [6020, 'Set Queue 2', 'Set Queue 2', 'Set Queue 2', 'Set Queue 2', :pvp, :tft, false, false],
      [6023, 'Set Queue 2 3v0', 'Set Queue 2 3v0', 'Set Queue 2 3v0', '', :pvp, :tft, false, false],
      [6025, 'Set Queue 2 1v7', 'Set Queue 2 1v7', 'Set Queue 2 1v7', 'Set Queue 2 1v7', :pvp, :tft, false, false],
      [6030, 'Set Queue 3', 'Set Queue 3', 'Set Queue 3', 'Set Queue 3', :pvp, :tft, false, false],
      [6031, 'Set 13 1v0', 'Set 13 1v0', 'Set 13 1v0', 'Set 13 1v0', :pvp, :tft, false, false],
      [6032, 'Set 13 2v0', 'Set 13 2v0', 'Set 13 2v0', 'Set 13 2v0', :pvp, :tft, false, false],
      [6033, 'Set 13 3v0', 'Set 13 3v0', 'Set 13 3v0', 'Set 13 3v0', :pvp, :tft, false, false],
      [6034, 'Set 13 4v0', 'Set 13 4v0', 'Set 13 4v0', 'Set 13 4v0', :pvp, :tft, false, false],
      [6035, 'Set Queue 3 1v7', 'Set Queue 3 1v7', 'Set Queue 3 1v7', 'Set Queue 3 1v7', :pvp, :tft, false, false],
      [6060, 'Set 13 Normal Hyper Roll', 'Set 13 Normal Hyper Roll', 'Set 13 Normal Hyper Roll', 'Set 13 Normal Hyper Roll', :pvp, :tft, false, false],
      [6061, 'Set 13 1v0 (Normal Hyper Roll)', 'Set 13 1v0 (Normal Hyper Roll)', 'Set 13 1v0 (Normal Hyper Roll)', 'Set 13 1v0 (Normal Hyper Roll)', :pvp, :tft, false, false],
      [6062, 'Set 13 2v0 (Normal Hyper Roll)', 'Set 13 2v0 (Normal Hyper Roll)', 'Set 13 2v0 (Normal Hyper Roll)', 'Set 13 2v0 (Normal Hyper Roll)', :pvp, :tft, false, false],
      [6063, 'Set 13 Double Up', 'Set 13 Double Up', 'Set 13 Double Up', 'Set 13 Double Up', :pvp, :tft, false, false],
      [6064, 'Set 13 2v0 (Double Up)', 'Set 13 2v0 (Double Up)', 'Set 13 2v0 (Double Up)', 'Set 13 2v0 (Double Up)', :pvp, :tft, false, false],
      [6065, 'Set 13 4v0 (Double Up)', 'Set 13 4v0 (Double Up)', 'Set 13 4v0 (Double Up)', 'Set 13 4v0 (Double Up)', :pvp, :tft, false, false],
      [6067, 'Set 13 1v0', 'Set 13 1v0', 'Set 13 1v0', 'Set 13 1v0', :pvp, :tft, false, false],
      [6071, '', '', '', '', :pvp, :other, false, false],
      [6072, '', '', '', '', :pvp, :other, false, false],
      [6073, '', '', '', '', :pvp, :other, false, false],
      [6075, '', '', '', '', :pvp, :other, false, false],
      [6081, '', '', '', '', :pvp, :other, false, false],
      [6082, '', '', '', '', :pvp, :other, false, false],
      [6092, '', '', '', '', :pvp, :other, false, false],
      [6094, '', '', '', '', :pvp, :other, false, false],
      [6100, 'CHONCC\'S K.O. COLISEUM', 'Choncc\'s K.O. Coliseum', 'Choncc\'s K.O. Coliseum', 'CHONCC\'S K.O. COLISEUM', :pvp, :tft, false, false],
      [6101, 'CHONCC\'S K.O. COLISEUM (1v0)', 'CHONCC\'S K.O. COLISEUM (1v0)', 'CHONCC\'S K.O. COLISEUM (1v0)', 'CHONCC\'S K.O. COLISEUM (1v0)', :pvp, :tft, false, false],
      [6102, 'CHONCC\'S K.O. COLISEUM (2v0)', 'CHONCC\'S K.O. COLISEUM (2v0)', 'CHONCC\'S K.O. COLISEUM (2v0)', 'CHONCC\'S K.O. COLISEUM (2v0)', :pvp, :tft, false, false],
      [6105, '', '', '', '', :pvp, :other, false, false],
      [6110, 'Set 17 (Normal)', 'Set 17 (Normal)', 'Set 17 (Normal)', 'SET 17 (NORMAL)', :pvp, :tft, true, false],
      [6111, '1v0 (Set 4.5 Revival)', '1v0 (Set 4.5 Revival)', '1v0 (Set 4.5 Revival)', '1v0 (Set 4.5 Revival)', :pvp, :tft, false, false],
      [6112, '2v0 (Set 4.5 Revival)', '2v0 (Set 4.5 Revival)', '2v0 (Set 4.5 Revival)', '2v0 (Set 4.5 Revival)', :pvp, :tft, false, false],
      [6115, '1v7 (Set 4.5 Revival)', '1v7 (Set 4.5 Revival)', '1v7 (Set 4.5 Revival)', '1v7 (Set 4.5 Revival)', :pvp, :tft, false, false],
      [6120, 'Pengu\'s Party', 'Pengu\'s Party', 'Pengu\'s Party', 'PENGU\'S PARTY', :pvp, :tft, false, false],
      [6121, '1v0 (PENGU\'S PARTY)', '1v0 (PENGU\'S PARTY)', '1v0 (PENGU\'S PARTY)', '1v0 (PENGU\'S PARTY)', :pvp, :tft, false, false],
      [6122, '2v0 (PENGU\'S PARTY)', '2v0 (PENGU\'S PARTY)', '2v0 (PENGU\'S PARTY)', '2v0 (PENGU\'S PARTY)', :pvp, :tft, false, false],
      [6125, '1v7 Bots (PENGU\'S PARTY)', '1v7 Bots (PENGU\'S PARTY)', '1v7 Bots (PENGU\'S PARTY)', '1v7 Bots (PENGU\'S PARTY)', :pvp, :tft, false, false],
      [6130, 'Ao Shin\'s Ascent', 'Ao Shin\'s Ascent', 'Ao Shin\'s Ascent', 'Ao Shin\'s Ascent', :pvp, :tft, false, false],
      [6140, '', '', '', '', :pvp, :other, false, false],
      [6141, '', '', '', '', :pvp, :other, false, false],
      [6142, '', '', '', '', :pvp, :other, false, false],
      [6220, '', '', '', '', :pvp, :other, false, false],
      [6300, '', '', '', '', :pvp, :other, false, false],
      [6310, '', '', '', '', :pvp, :other, false, false],
      [6320, '', '', '', '', :pvp, :other, false, false],
      [7001, '', '', '', '', :pvp, :other, false, false],
      [7011, 'TFT Cosmetics Asset Viewer', 'TFT Cosmetics Asset Viewer', 'TFT Cosmetics Asset Viewer', '', :pvp, :tft, false, false],
      [7021, '', '', '', '', :pvp, :other, false, false],
      [7022, '', '', '', '', :pvp, :other, false, false],
      [9001, '', '', '', '', :pvp, :other, false, false]
    ].freeze

    INDEX = ROWS.each_with_object({}) { |row, map| map[row[0]] = Queue.new(*row) }.freeze
    QUEUES = INDEX.values.freeze
  end
end
